name: sync to GCS

on:
  push:
    branches:
      - shopping  # 或你想要同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          credentials_json: ${{ secrets. }}

      - name: sync to GCS
        run: |
          gsutil -m rsync -r . gs://tir102-spotify-test
